### ISSUE TITLE
Admin console

### ISSUE THREAD

**Issue by YiwenDong98** [CastleKey/webdev_team_project#6]
Need admin console for admins to change user role

**Comment by cwaj400** [comment]
Do I clone this project and then work on it?

**Comment by TheGuy191919** [comment]
Steps  
 - git clone https://github.com/CastleKey/webdev_team_project.git
 - git branch NEW_BRANCH_NAME
 - git checkout NEW_BRANCH_NAME
~~~~~~~~
Code some stuff
~~~~~~~~
 - git add FILES_YOU_WORKED_ON
 - git commit
~~~~~~
Type out a commit message and save
~~~~~~
 - git push -u origin NEW_BRANCH_NAME
Though Izaak is working on this issue. You're free to work on any of the other issues. Text me if you got other questions.
